import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const urls = {
  scrapbox: "https://scrapbox.io/niboshi/niboshi",
  twitter: "https://twitter.com/mpppk",
  github: "https://github.com/mpppk",
};

const Home: NextPage = () => {
  useEffect(() => {
    console.log(location);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>nibo.sh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href={urls.scrapbox} />
        <link rel="preconnect" href={urls.twitter} />
        <link rel="preconnect" href={urls.github} />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Image
            className={"niboshi-logo"}
            src="https://i.gyazo.com/eafa8efaaad66776e010ec9123d28f9e.png"
            alt={"niboshi profile icon"}
            width={64}
            height={64}
          />
          <span>nibo.sh/</span>
        </h1>

        <div className={styles.grid}>
          <a
            href={urls.scrapbox}
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>Profile</h2>
            <p>/niboshi on Scrapbox</p>
          </a>

          <a
            href={urls.twitter}
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>Twitter</h2>
            <p>@mpppk</p>
          </a>

          <a
            href={urls.github}
            className={styles.card}
            target="_blank"
            rel="noreferrer"
          >
            <h2>GitHub</h2>
            <p>@mpppk</p>
          </a>

          <Link href={"/pay"}>
            <a className={styles.card}>
              <h2>Pay</h2>
              <p>Kyash, PayPay</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
